### ISSUE TITLE
TalkGroup Monitoring & Simpler Configuration

### ISSUE THREAD

**Issue by mholttech** [KN4KNG/OP25_GUI#3]
Hi Alex,

I've taken your code and refactored it to be simpler to modify and include a screen for displaying the active TalkGroup.  My setup runs on a 3.5in Screen as well which is different from your 7in.  You can see my code at https://github.com/mholt-io/op25-scripts

**Comment by KN4KNG** [comment]
Great! I'll take a look into it. I was hoping to have more time for this project, unfortunately I can't support it while juggling work, and family. I hope people with better programming experience than I can make this better. I just made my last commit for the moment to clean up the project and include install instructions. 

Please keep me up to date with your project! email me anytime at KN4KNG@outlook.com

**Comment by KN4KNG** [comment]
Issue fixed/improved in mholttech's repo: https://github.com/mholt-io/op25-scripts
